xcodeproj 'Tests'
workspace '../PFIncrementalStore'
inhibit_all_warnings!

def import_pods
  pod 'Kiwi/XCTest', '=2.2.3'
  pod 'PFIncrementalStore', :path => "../"
end

target :ios, exclusive: true do
  platform :ios, '7.0'
  link_with 'iOS Test'
  import_pods
end
