xcodeproj 'Tests'
workspace '../PFIncrementalStore'
inhibit_all_warnings!

def import_pods
  pod 'PFIncrementalStore', :path => '../'
end

target :ios, exclusive: true do
  platform :ios, '7.0'
  link_with 'iOS Test'
  import_pods
end
